Fix: improve hover text 'unknown' for better UX.
RequestNetwork/request-apps pull request #47
Opened 2023-01-02 07:15 UTC by PijiDev

2023-01-02 16:10 UTC, MantisClone requested changes

2023-01-02 16:10 UTC, MantisClone commented on packages/shared/src/index.tsx
> -  | "unknown";
@PijiDev Please revert this. This change doesn't successfully build.

```console
mantisclone@mantisclone-Inspiron-7620:~/projects/request-apps-piji$ yarn workspaces run build
yarn workspaces v1.22.19

> request-shared
yarn run v1.22.19
$ tsc
src/helpers/parseRequest.ts:75:5 - error TS2322: Type '"unknown" | "canceled" | "paid" | "overpaid" | "pending" | "open"' is not assignable to type 'RequestStatus'.
  Type '"unknown"' is not assignable to type 'RequestStatus'.

75     status,
       ~~~~~~

  src/index.tsx:18:3
    18   status: RequestStatus;
         ~~~~~~
    The expected type comes from property 'status' which is declared here on type 'IParsedRequest'


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 2
Command: /home/mantisclone/.nvm/versions/node/v18.12.1/bin/node
Arguments: /home/mantisclone/.nvm/versions/node/v18.12.1/lib/node_modules/yarn/lib/cli.js run build
Directory: /home/mantisclone/projects/request-apps-piji/packages/shared
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspaces for documentation about this command.
```

2023-01-02 16:10 UTC, MantisClone commented on packages/request-ui/src/RStatusBadge.tsx
> -          props.status === 'unknown'
Please also revert this line from 'waiting' to 'unknown'

2023-01-02 18:17 UTC, MantisClone requested changes

2023-01-02 18:17 UTC, MantisClone commented on packages/request-ui/src/RStatusBadge.tsx
> +  waiting: 'Waiting',
```suggestion
  waiting: 'Creating Request ',
```

2023-01-02 18:17 UTC, MantisClone commented on packages/request-ui/src/RStatusBadge.tsx
> +          props.status === 'waiting'
```suggestion
          props.status === 'unknown'
```

2023-01-02 18:17 UTC, MantisClone commented on packages/shared/src/index.tsx
> +  | "waiting";
@PijiDev Please revert this. This change doesn't successfully build.

```suggestion
  | "unknown";
```

```console
mantisclone@mantisclone-Inspiron-7620:~/projects/request-apps-piji$ yarn workspaces run build
yarn workspaces v1.22.19

> request-shared
yarn run v1.22.19
$ tsc
src/helpers/parseRequest.ts:75:5 - error TS2322: Type '"unknown" | "canceled" | "paid" | "overpaid" | "pending" | "open"' is not assignable to type 'RequestStatus'.
  Type '"unknown"' is not assignable to type 'RequestStatus'.

75     status,
       ~~~~~~

  src/index.tsx:18:3
    18   status: RequestStatus;
         ~~~~~~
    The expected type comes from property 'status' which is declared here on type 'IParsedRequest'


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 2
Command: /home/mantisclone/.nvm/versions/node/v18.12.1/bin/node
Arguments: /home/mantisclone/.nvm/versions/node/v18.12.1/lib/node_modules/yarn/lib/cli.js run build
Directory: /home/mantisclone/projects/request-apps-piji/packages/shared
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspaces for documentation about this command.
```

2023-01-04 05:53 UTC, PijiDev commented
The build now works, for now I kept the ` ? 'The balance computation might have failed'`, because the original code expects a conditional string.

2023-01-15 18:31 UTC, MantisClone requested changes
Thanks for taking a second look at this.  I like that you changed the state name from `unknown` to `waiting`. However, I think the hover text can still be improved.

2023-01-15 18:31 UTC, MantisClone commented on packages/request-ui/src/RStatusBadge.tsx
> +          ? 'The balance computation might have failed'
```suggestion
          ? 'Waiting for request to be stored in IPFS'
```

2023-01-16 21:03 UTC, MantisClone approved these changes

2023-01-16 21:03 UTC, merged